[package]
name = "mandelbrot-cuda"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.6"
num-complex = "0.4.3"
cuda-runtime-sys = "0.3.0-alpha.1"
rayon = "1.5"
crossbeam-channel = "0.5"
gif = "0.11"
parking_lot = "0.11.1"

[build-dependencies]
cc = "1.0"